--DROP TABLE

--TABELA CLINICA
CREATE TABLE CLINICA(
	IDCLINICA			UNIQUEIDENTIFIER				NOT NULL,
	NOME				NVARCHAR(150)					NOT NULL,
	CODIGO				NVARCHAR(15)					NOT NULL,
	CNPJ				NVARCHAR(14)					NOT NULL,
	RUA					NVARCHAR(150)					NOT NULL,
	NUMERO				NVARCHAR(14)					NOT NULL,
	BAIRRO				NVARCHAR(150)					NOT NULL,
	CIDADE				NVARCHAR(150)					NOT NULL,
	UF					NVARCHAR(150)					NOT NULL,
	CEP					NVARCHAR(150)					NOT NULL,
	PRIMARY KEY(IDCLINICA))
GO

--TABELA MEDICO
CREATE TABLE MEDICO(
	IDMEDICO			UNIQUEIDENTIFIER				NOT NULL,
	NOME				NVARCHAR(150)					NOT NULL,
	CPF					NVARCHAR(11)					NOT NULL,
	MATRICULA			NVARCHAR(15)					NOT NULL,
	EMAIL				NVARCHAR(150)					NOT NULL,
	TELEFONE			NVARCHAR(14)					NOT NULL,
	PRIMARY KEY(IDMEDICO))
GO

--TABELA PACIENTE
CREATE TABLE PACIENTE(
	IDPACIENTE			UNIQUEIDENTIFIER				NOT NULL,
	NOME				NVARCHAR (150)					NOT NULL,
	CPF					NVARCHAR(15)					NOT NULL,
	EMAIL				NVARCHAR(14)					NOT NULL,
	TELEFONE			NVARCHAR(150)					NOT NULL,
	RUA					NVARCHAR(14)					NOT NULL,
	NUMERO				NVARCHAR(150)					NOT NULL,
	BAIRRO				NVARCHAR(150)					NOT NULL,
	CIDADE				NVARCHAR(150)					NOT NULL,
	UF					NVARCHAR(150)					NOT NULL,
	CEP					NVARCHAR(150)					NOT NULL,
	DATANASCIMENTO		DATETIME						NOT NULL,
	MEDICOID			UNIQUEIDENTIFIER				NOT NULL,
	PRIMARY KEY(IDPACIENTE),
	FOREIGN KEY(MEDICOID) REFERENCES MEDICO(IDMEDICO))
GO

--TABELA CLINICAMEDICO
CREATE TABLE CLINICAMEDICO(
	IDCLINICAMEDICO		UNIQUEIDENTIFIER				NOT NULL,
	CLINICAID			UNIQUEIDENTIFIER				NOT NULL,
	MEDICOID			UNIQUEIDENTIFIER				NOT NULL,
	PRIMARY KEY(IDCLINICAMEDICO),
	FOREIGN KEY(MEDICOID) REFERENCES MEDICO(IDMEDICO),
	FOREIGN KEY(CLINICAID) REFERENCES CLINICA(IDCLINICA))
GO

-- PROC INSERIR CLINICA
CREATE PROCEDURE SP_INSERIRCLINICA				 
	@NOME				NVARCHAR(150),					 
	@CODIGO				NVARCHAR(15),					
	@CNPJ				NVARCHAR(14),				
	@RUA				NVARCHAR(150),				
	@NUMERO				NVARCHAR(14),				
	@BAIRRO				NVARCHAR(150),				
	@CIDADE				NVARCHAR(150),					
	@UF					NVARCHAR(150),					
	@CEP				NVARCHAR(150)
AS 
BEGIN
	BEGIN TRANSACTION
		INSERT INTO CLINICA(IDCLINICA, NOME, CODIGO, CNPJ, RUA, NUMERO, BAIRRO, CIDADE, UF, CEP)
		VALUES(NEWID(), @NOME, @CODIGO, @CNPJ, @RUA, @NUMERO, @BAIRRO, @CIDADE, @UF,  @CEP)
	COMMIT
END
GO

-- PROC INSERIR PACIENTE
CREATE PROCEDURE SP_INSERIRPACIENTE				 
	@NOME				NVARCHAR (150),
	@CPF				NVARCHAR(15),
	@EMAIL				NVARCHAR(14),
	@TELEFONE			NVARCHAR(150),
	@RUA				NVARCHAR(14),
	@NUMERO				NVARCHAR(150),
	@BAIRRO				NVARCHAR(150),
	@CIDADE				NVARCHAR(150),
	@UF					NVARCHAR(150),
	@CEP				NVARCHAR(150),
	@DATANASCIMENTO		DATETIME,
	@MEDICOID			UNIQUEIDENTIFIER
AS 
BEGIN
	BEGIN TRANSACTION
		INSERT INTO PACIENTE(IDPACIENTE, NOME, CPF, EMAIL, TELEFONE, RUA, NUMERO, BAIRRO, CIDADE, UF, CEP, DATANASCIMENTO, MEDICOID)
		VALUES(NEWID(), @NOME, @CPF, @EMAIL, @TELEFONE, @RUA, @NUMERO, @BAIRRO, @CIDADE, @UF,  @CEP, @DATANASCIMENTO, @MEDICOID)
	COMMIT
END
GO

--PROC INSERIR MEDICO
CREATE PROCEDURE SP_INSERIRMEDICO				 
	@NOME				NVARCHAR(150),
	@CPF				NVARCHAR(11),
	@MATRICULA			NVARCHAR(15),
	@EMAIL				NVARCHAR(150),
	@TELEFONE			NVARCHAR(14)
AS 
BEGIN
	BEGIN TRANSACTION
		INSERT INTO MEDICO(IDMEDICO, NOME, CPF, MATRICULA, EMAIL, TELEFONE)
		VALUES(NEWID(), @NOME, @CPF, @MATRICULA, @EMAIL, @TELEFONE)
	COMMIT
END
GO

--PROC INSERIR CLINICAMEDICO
CREATE PROCEDURE SP_INSERIRCLINICAMEDICO				 
	@MEDICOID			UNIQUEIDENTIFIER,
	@CLINICAID			UNIQUEIDENTIFIER
AS 
BEGIN
	BEGIN TRANSACTION
		INSERT INTO CLINICAMEDICO(IDCLINICAMEDICO, MEDICOID, CLINICAID)
		VALUES(NEWID(), @MEDICOID, @CLINICAID)
	COMMIT
END
GO

--PROC EXCLUIR CLINICA
CREATE PROCEDURE SP_EXCLUIRCLINICA
	@IDCLINICA			UNIQUEIDENTIFIER
AS 
BEGIN
	BEGIN TRANSACTION
		DELETE CLINICA	WHERE IDCLINICA = @IDCLINICA		
	COMMIT
END
GO

--PROC EXCLUIR CLINICAMEDICO
CREATE PROCEDURE SP_EXCLUIRCLINICAMEDICO
	@IDCLINICAMEDICO			UNIQUEIDENTIFIER
AS 
BEGIN
	BEGIN TRANSACTION
		DELETE CLINICAMEDICO	WHERE IDCLINICAMEDICO = @IDCLINICAMEDICO		
	COMMIT
END
GO

--PROC EXCLUIR PACIENTE
CREATE PROCEDURE SP_EXCLUIRPACIENTE
	@IDPACIENTE			UNIQUEIDENTIFIER
AS 
BEGIN
	BEGIN TRANSACTION
		DELETE PACIENTE	WHERE IDPACIENTE = @IDPACIENTE		
	COMMIT
END
GO

--PROC EXCLUIR MEDICO
CREATE PROCEDURE SP_EXCLUIRMEDICO
	@IDMEDICO			UNIQUEIDENTIFIER
AS 
BEGIN
	BEGIN TRANSACTION
		DELETE MEDICO	WHERE IDMEDICO = @IDMEDICO		
	COMMIT
END
GO

--PROC ATUALIZAR CLINICA
CREATE PROCEDURE SP_ATUALIZARCLINICA
	@IDCLINICA			UNIQUEIDENTIFIER,
	@NOME				NVARCHAR(150),					 
	@CODIGO				NVARCHAR(15),					
	@CNPJ				NVARCHAR(14),				
	@RUA				NVARCHAR(150),				
	@NUMERO				NVARCHAR(14),				
	@BAIRRO				NVARCHAR(150),				
	@CIDADE				NVARCHAR(150),					
	@UF					NVARCHAR(150),					
	@CEP				NVARCHAR(150)
AS 
BEGIN
	BEGIN TRANSACTION
		UPDATE CLINICA
			SET
				NOME = @NOME,									 
				CODIGO = @CODIGO,								
				CNPJ = @CNPJ,							
				RUA = @RUA,							
				NUMERO = @NUMERO,								
				BAIRRO = @BAIRRO,							
				CIDADE = @CIDADE,									
				UF = @UF,										
				CEP = @CEP
			WHERE
				IDCLINICA = @IDCLINICA
				
	COMMIT
END
GO

--PROC ATUALIZAR PACIENTE
CREATE PROCEDURE SP_ATUALIZARPACIENTE
	@IDPACIENTE			UNIQUEIDENTIFIER,
	@NOME				NVARCHAR (150),
	@CPF				NVARCHAR(15),
	@EMAIL				NVARCHAR(14),
	@TELEFONE			NVARCHAR(150),
	@RUA				NVARCHAR(14),
	@NUMERO				NVARCHAR(150),
	@BAIRRO				NVARCHAR(150),
	@CIDADE				NVARCHAR(150),
	@UF					NVARCHAR(150),
	@CEP				NVARCHAR(150),
	@DATANASCIMENTO		DATETIME,
	@MEDICOID			UNIQUEIDENTIFIER
AS 
BEGIN
	BEGIN TRANSACTION
		UPDATE PACIENTE
			SET
				NOME = @NOME,
				CPF = @CPF,
				EMAIL = @EMAIL,
				TELEFONE = @TELEFONE,
				RUA = @RUA,
				NUMERO = @NUMERO,
				BAIRRO = @BAIRRO,
				CIDADE = @CIDADE,
				UF = @UF,
				CEP = @CEP,
				DATANASCIMENTO = @DATANASCIMENTO,
				MEDICOID = @MEDICOID
			WHERE
				IDPACIENTE = @IDPACIENTE
				
	COMMIT
END
GO

--PROC ATUALIZAR MEDICO
CREATE PROCEDURE SP_ATUALIZARMEDICO
	@IDMEDICO			UNIQUEIDENTIFIER,
	@NOME				NVARCHAR(150),
	@CPF				NVARCHAR(11),
	@MATRICULA			NVARCHAR(15),
	@EMAIL				NVARCHAR(150),
	@TELEFONE			NVARCHAR(14)
AS 
BEGIN
	BEGIN TRANSACTION
		UPDATE MEDICO
			SET
				NOME = @NOME,									 
				CPF = @CPF,								
				MATRICULA = @MATRICULA,							
				EMAIL = @EMAIL,							
				TELEFONE = @TELEFONE								
			WHERE
				IDMEDICO = @IDMEDICO		
	COMMIT
END
GO

--PROC ATUALIZAR CLINICAMEDICO
CREATE PROCEDURE SP_ATUALIZARCLINICAMEDICO
	@IDCLINICAMEDICO	UNIQUEIDENTIFIER,
	@MEDICOID			UNIQUEIDENTIFIER,
	@CLINICAID			UNIQUEIDENTIFIER
	
AS 
BEGIN
	BEGIN TRANSACTION
		UPDATE CLINICAMEDICO
			SET
					MEDICOID = @MEDICOID,
					CLINICAID = @CLINICAID
			WHERE
				IDCLINICAMEDICO = @IDCLINICAMEDICO		
	COMMIT
END
GO





